In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4]

In [3]:
np.array(my_list)

array([1, 2, 3, 4])

In [5]:
myarr = np.array(my_list)

In [7]:
myarr

array([1, 2, 3, 4])

In [8]:
type(myarr)

numpy.ndarray

In [18]:
np.random.rand(3,3)

array([[0.06425473, 0.50576915, 0.53536774],
       [0.76330661, 0.60532582, 0.47829187],
       [0.64413857, 0.89394172, 0.84393922]])

In [20]:
np.random.randn(4,2)

array([[-1.21887866,  0.05624607],
       [ 0.14585986, -1.32667413],
       [ 0.06148906,  0.51902061],
       [ 1.36685223, -1.30291632]])

In [24]:
np.random.randint(0,9,(3,3))

array([[3, 3, 8],
       [7, 6, 8],
       [4, 6, 8]])

In [25]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [33]:
myarray = np.linspace(0,10,101)

In [34]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr_2d.shape

(3, 3)

In [14]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr = np.arange(1,11)

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [20]:
bool_arr = arr >4

In [21]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [22]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [23]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [24]:
import numpy as np

In [25]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

# total_rolls_over_two = # This should be a single integer

In [32]:
total_rolls_over_two= len(dice_rolls[dice_rolls> 2])

In [33]:
total_rolls_over_two

19

In [34]:
# TASK: Use numpy to check the total remaining in the account after the series of transactions.
# NOTE: Many different ways to do this! 
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
# Link to Solution: https://gist.github.com/Pierian-Data/225a449484e12e0535fbbac2231b426b

import numpy as np
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

account_total = account_transactions.sum()

In [35]:
account_total

2720